book(neil_gaiman, american_gods).
book(neil_gaiman, anansi_boys).
book(arthur_c_clarke, childhoods_end).
book(neal_stephenson, snowcrash).
book(frank_herbert, dune).
book(gene_wolfe, book_of_the_new_sun).
book(gene_wolfe, urth_of_the_new_sun).
book(joseph_campbell, masks_of_god).
book(joseph_campbell, hero_with_a_thousands_faces).